language: r
warnings_are_errors: false
sudo: required
cache: packages
before_install:
  - chmod a+x ./RunScript.sh
install:
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e 'source("test.R")'
script:
  - ./RunScript.sh